version: '3'
services:

    pg:
        image: postgres:10.6-alpine
        restart: unless-stopped
        volumes:
            - ./pg-data:/var/lib/postgresql/data
            - ./backend/pg:/docker-entrypoint-initdb.d
        expose:
            - 5432
        ports:
            - 9998:5432
        networks:
            - app
        environment:
            POSTGRES_USER       : backend
            POSTGRES_PASSWORD   : backend
            POSTGRES_DB         : app

    backend:
        image: node:10.14.1-alpine
        restart: unless-stopped
        depends_on:
            - pg
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 9999:9999
        working_dir: /usr/src/app
        command: [ "sh", "-c", "yarn && yarn start" ]
        networks:
            - app
        environment:
            NODE_ENV    : development
            PGHOST      : pg
            PGUSER      : backend
            PGPASSWORD  : backend
            PGDATABASE  : app

networks:
    app:
        driver: bridge
